# Generated by Django 5.1.4 on 2025-01-07 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todoitem",
            options={"ordering": ("id",), "verbose_name": "TODO Item"},
        ),
    ]
