# Generated by Django 5.1.4 on 2025-01-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list", "0002_alter_todoitem_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
